"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](bg:color_bg1 fg:color_bg1)\
$os\
$username\
[](bg:color_yellow fg:color_bg1)\
$directory\
[](fg:color_yellow bg:color_fg0)\
$git_branch\
$git_status\
[](fg:color_fg0 bg:color_green)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_green bg:color_blue)\
$kubernetes\
$docker_context\
$conda\
[](fg:color_blue bg:color_bg1)\
$time\
[](fg:color_bg1)\
$line_break\
$character\
"""

palette = 'nord'

[palettes.nord]
color_fg0 = '#D8DEE9'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#81A1C1'
color_aqua = '#88C0D0'
color_green = '#A3BE8C'
color_orange = '#d65d0e'
color_purple = '#B48EAD'
color_red = '#BF616A'
color_yellow = '#EBCB8B'

[os]
disabled = false
style = "bg:color_bg1 fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_bg1 fg:color_fg0"
style_root = "bg:color_bg1 fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_bg1 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
fish_style_pwd_dir_length = 4
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "fg:color_bg1 bg:color_fg0"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:color_bg1 bg:color_fg0"
format = '[($all_status$ahead_behind )]($style)'

[nodejs]
symbol = ""
style = "fg:color_bg1 bg:color_green"
format = '[ $symbol( $version) ]($style)'

[c]
symbol = " "
style = "fg:color_bg1 bg:color_green"
format = '[ $symbol( $version) ]($style)'

[rust]
symbol = ""
style = "fg:color_bg1 bg:color_green"
format = '[ $symbol( $version) ]($style)'

[golang]
symbol = ""
style = "fg:color_bg1 bg:color_green"
format = '[ $symbol( $version) ]($style)'

[php]
symbol = ""
style = "fg:color_bg1 bg:color_green"
format = '[ $symbol( $version) ]($style)'

[java]
symbol = " "
style = "fg:color_bg1 bg:color_green"
format = '[ $symbol( $version) ]($style)'

[kotlin]
symbol = ""
style = "fg:color_bg1 bg:color_green"
format = '[ $symbol( $version) ]($style)'

[haskell]
symbol = ""
style = "fg:color_bg1 bg:color_green"
format = '[ $symbol( $version) ]($style)'

[python]
symbol = ""
style = "fg:color_bg1 bg:color_green"
format = '[ $symbol( $version) ]($style)'

[docker_context]
symbol = ""
style = "fg:color_bg1 bg:color_blue"
format = '[ $symbol( $context) ]($style)'

[kubernetes]
disabled = false
symbol = "󱃾"
style = "fg:color_bg1 bg:color_blue"
format = '[ $symbol $context( \($namespace\)) ]($style)'

[conda]
style = "fg:color_bg1 bg:color_blue"
format = '[ $symbol( $environment) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:color_fg0 bg:color_bg1"
format = '[  $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'